const codes = {
  DEFFAULT: 'UNKNOWN_ERROR',
  MISSING_CONFIG: 'MISSING_CONFIGURATION',
  INVALID_BASE_URL: 'INVALID_BASE_URL',
  INVALID_AUTH_CONFIG: 'INVALID_AUTH_CONFIGURATION'
};

export default codes;
